# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4877488468714d25d3c1e71c5d491df85102181430aa9038df2b70c661491837688235fe053603a6affa58a6befaac92821690a9e79233c9b1fe6b03d34f1d30

test:
  secret_key_base: 80dc2e71fd3b6d3aadfd8593bb26407931e9ebdcfd9aca1ee7cf3a0125e2c8bc0b611afe23729e18ff9c8ce7d6e0ff207258411422c19fa44e51504ce224125d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
